Repository spacemeshos/go-spacemesh, pull requests merged in 2021-07, with the labels that each got.

#2481 Testnet 134 Candidate
  activation/activation.go
  activation/activation_test.go
  activation/activationdb_test.go
  activation/atxdb.go
  cmd/hare/hare.go
  cmd/hare/oracle.go
  cmd/node/oracle.go
  eligibility/fixedoracle.go
  hare/algorithm.go
  hare/broker.go
  hare/broker_test.go
  hare/eligibility/oracle.go
  hare/eligibility/oracle_test.go
  hare/flows_test.go
  hare/hare.go
  hare/mock_oracle.go
  hare/preroundtracker.go
  p2p/gossip/protocol.go
  p2p/switch.go
  sync/fetch_queue.go
  sync/syncer.go
  sync/validation_queue.go
  tortoise/ninja_tortoise.go
Labels: testnet

#2496 Testnet hotfix: Warm active set cache for hare
  hare/eligibility/oracle.go
  hare/eligibility/oracle_test.go
Labels: Hare Protocol, testnet, testnet_hotfix

#2473 updated Makefile & Dockerfiles
  DockerFileTests
  Dockerfile
  DockerfilePrebuiltBinary
  Makefile
  Makefile.Inc
  activation/activation.go
  activation/poetdb.go
  activation/post.go
  cmd/node/app_test.go
  cmd/root.go
  go.mod
  go.sum
  layerfetcher/blocks.go
  p2p/switch.go
  scripts/check-go-version.go
  scripts/check-go-version.sh
  scripts/win/check-go-version.ps1
  tests/Pipfile.lock
  tests/block_atx/add_node/config.yaml
  tests/block_atx/remove_node/config.yaml
  tests/config.yaml
  tests/k8s/bootstrapoet-w-conf.yml
  tests/k8s/client-w-conf.yml
  tests/late_nodes/delayed_config.yaml
  tests/setup_utils.py
  tests/tx_generator/config.yaml
Labels: v0.2
